spring.datasource.url=jdbc:mariadb://localhost:3306/sello_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false

# MAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subastasya.sistema@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Show error messages
server.error.include-message=always
server.error.include-exception=true

# Mercado Pago Configuration
mercadopago.access-token=TEST-ec85b80f-558c-45b2-a6cd-071df1fd637b
mercadopago.public-key=TEST-6281816190072559-060820-7f041c2f9c198aa7db0a5c7d8e7a3a26-1436955656
