spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false

# MAIL CONFIGURATION (GOOGLE APPS SCRIPT)
google.script.url=https://script.google.com/macros/s/AKfycbxiIP0HRx_zcmGvui9FQr4ueyyB1vnHxee-dHH_NJEvx_aDh_Smh_AUmSBxZZSBp3OuIQ/exec

# Show error messages
server.error.include-message=always
server.error.include-exception=true

# Mercado Pago Configuration
mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.public-key=${MERCADOPAGO_PUBLIC_KEY}
